import { useState, useEffect } from 'react';

/**
 * Custom hook to load photos from the public/photos directory
 * Uses optimized versions for thumbnails, originals for full-quality viewing
 * Manifest is auto-generated by the Vite plugin
 */
export function usePhotos() {
  const [photos, setPhotos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadPhotos() {
      try {
        // Fetch the auto-generated manifest file
        const response = await fetch('/photos/manifest.json');
        
        if (!response.ok) {
          setPhotos([]);
          setLoading(false);
          return;
        }

        const manifest = await response.json();
        
        // Convert manifest entries to photo objects
        // Use optimized for src (dome gallery), original for full-quality viewing
        const photoObjects = manifest.photos.map(photo => {
          const filename = photo.filename;
          const alt = filename
            .replace(/\.[^/.]+$/, '') // Remove extension
            .replace(/[-_]/g, ' ') // Replace hyphens and underscores with spaces
            .replace(/\b\w/g, char => char.toUpperCase()); // Capitalize first letter of each word

          return {
            src: photo.optimized, // Use optimized version for dome gallery (fast loading)
            srcOriginal: photo.original, // Keep original path for full-quality viewing
            alt: alt
          };
        });

        setPhotos(photoObjects);
        setLoading(false);

        // Preload optimized images in the background so they're cached
        // when the user navigates to the photography tab
        preloadImages(photoObjects);
      } catch (err) {
        setError(err.message);
        setPhotos([]);
        setLoading(false);
      }
    }

    loadPhotos();
  }, []);

  return { photos, loading, error };
}

/**
 * Silently preloads images in the background using requestIdleCallback
 * and staggered loading to avoid blocking the main thread.
 * Images are loaded via the Image() constructor which populates the browser cache.
 */
function preloadImages(photoObjects) {
  const STAGGER_MS = 150; // Delay between each image to avoid network contention

  const startPreloading = () => {
    photoObjects.forEach((photo, index) => {
      setTimeout(() => {
        const img = new Image();
        img.src = photo.src; // Preload optimized version (used in gallery)
      }, index * STAGGER_MS);
    });
  };

  // Use requestIdleCallback to wait until the browser is idle
  // Falls back to a 2-second delay for browsers that don't support it
  if ('requestIdleCallback' in window) {
    requestIdleCallback(startPreloading, { timeout: 5000 });
  } else {
    setTimeout(startPreloading, 2000);
  }
}
