import { useState, useEffect } from 'react';

/**
 * Custom hook to load photos from the public/photos directory
 * Uses optimized versions for thumbnails, originals for full-quality viewing
 * Manifest is auto-generated by the Vite plugin
 */
export function usePhotos() {
  const [photos, setPhotos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadPhotos() {
      try {
        // Fetch the auto-generated manifest file
        const response = await fetch('/photos/manifest.json');
        
        if (!response.ok) {
          setPhotos([]);
          setLoading(false);
          return;
        }

        const manifest = await response.json();
        
        // Convert manifest entries to photo objects
        // Use optimized for src (dome gallery), original for full-quality viewing
        const photoObjects = manifest.photos.map(photo => {
          const filename = photo.filename;
          const alt = filename
            .replace(/\.[^/.]+$/, '') // Remove extension
            .replace(/[-_]/g, ' ') // Replace hyphens and underscores with spaces
            .replace(/\b\w/g, char => char.toUpperCase()); // Capitalize first letter of each word

          return {
            src: photo.optimized, // Use optimized version for dome gallery (fast loading)
            srcOriginal: photo.original, // Keep original path for full-quality viewing
            alt: alt
          };
        });

        setPhotos(photoObjects);
        setLoading(false);
      } catch (err) {
        setError(err.message);
        setPhotos([]);
        setLoading(false);
      }
    }

    loadPhotos();
  }, []);

  return { photos, loading, error };
}
